### ISSUE TITLE
Tap ./gradlew clean distJar 도중 오류

### ISSUE THREAD

**Issue by ghost** [noonmaru/tap#1]

**Comment by Apple6050** [comment]
> Task :v1_13_R1:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':v1_13_R1:compileKotlin'.
> Could not resolve all files for configuration ':v1_13_R1:compileClasspath'.
   > Could not find org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.jar
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.jar
       - https://oss.sonatype.org/content/groups/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/groups/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - https://oss.sonatype.org/content/groups/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.jar
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.jar
       - https://jitpack.io/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - https://jitpack.io/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.jar
       - file:/C:/Users/user/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/user/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - file:/C:/Users/user/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.jar
     Required by:
         project :v1_13_R1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
11 actionable tasks: 8 executed, 3 up-to-date
이라고 뜨면서 빌드가 않되요 ㅠㅠㅠ 도와주세요

**Comment by Apple6050** [comment]
도와주세요

**Comment by Apple6050** [comment]
patrick-mc님의 글을 보고 버그 고쳤습니다.
patrick-mc님 감사합니다.

**Comment by Apple6050** [comment]
> Task :v1_13_R1:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':v1_13_R1:compileKotlin'.
> Could not resolve all files for configuration ':v1_13_R1:compileClasspath'.
   > Could not resolve org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
     Required by:
         project :v1_13_R1
      > Could not resolve org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
         > Unable to load Maven meta-data from https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'. Received status code 500 from server: javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'component' due to limited free space on the disk (2956 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .??        DB name="component"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 53s
11 actionable tasks: 6 executed, 5 up-to-date
라고 뜨며 tap가 빌드각 않됩니다
시스템 정보
OS: Windows 10
Java: JDK_1.8.0_251,Java SE 1.8.0_251
사용 중입니다
도와주세요

**Comment by Apple6050** [comment]
Patrick-mc님 도와주세요

**Comment by patrick-choe** [comment]
https://github.com/noonmaru/tap/blob/master/readme.md#gradle
nms 구현체 필요할때 사용하는 방법 readme에 적혀 있습니다. 참고 바랍니다.
단순히 jar이 필요한 것이라면 (프로젝트가 필요한 것이 아니라면) [릴리즈](https://github.com/noonmaru/tap/releases/) 에서 dist jar을 받아서 사용하시면 됩니다.

**Comment by Apple6050** [comment]
@patrick-mc 
https://github.com/noonmaru/tap/blob/master/readme.md#gradle
를 확인해도 내용을 알 수 없습니다.
도와주세요

**Comment by Apple6050** [comment]
user@USER-PC1 MINGW64 /d/Desktop/tap-2.3.1
$ ./gradlew clean distJar
> Task :v1_13_R1:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':v1_13_R1:compileKotlin'.
> Could not resolve all files for configuration ':v1_13_R1:compileClasspath'.
   > Could not resolve org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
     Required by:
         project :v1_13_R1
      > Could not resolve org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
         > Unable to load Maven meta-data from https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'. Received status code 500 from server: javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'component' due to limited free space on the disk (2657 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .??        DB name="component"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
11 actionable tasks: 7 executed, 4 up-to-date
오류
해석해보니
user @ USER-PC1 MINGW64 /d/Desktop/tap-2.3.1
$ ./gradlew clean distJar
> 작업 : v1_13_R1 : compileKotlin FAILED

실패 : 예외로 인해 빌드가 실패했습니다.

* 무엇이 잘못 되었습니까?
태스크 ': v1_13_R1 : compileKotlin'에 대한 실행에 실패했습니다.
> 구성 ': v1_13_R1 : compileClasspath'에 대한 모든 파일을 확인할 수 없습니다.
   > org.spigotmc : spigot : 1.13.2-R0.1-SNAPSHOT를 해결할 수 없습니다.
     필수 :
         프로젝트 : v1_13_R1
      > org.spigotmc : spigot : 1.13.2-R0.1-SNAPSHOT를 해결할 수 없습니다.
         > https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml에서 Maven 메타 데이터를로드 할 수 없습니다.
            > 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'리소스를 가져올 수 없습니다.
               > 'https://repo.dmulloy2.net/nexus/repository/public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml'을 가져올 수 없습니다. 서버에서 상태 코드 500을 수신했습니다. javax.servlet.ServletException : com.orientechnologies.orient.core.exception.OLowDiskSpaceException : 디스크의 여유 공간이 제한되어서 'component'데이터베이스에 대한 쓰기 조작을 실행하는 중에 오류가 발생했습니다 (2657MB). 데이터베이스가 이제 읽기 전용 모드로 작동 중입니다. 데이터베이스를 닫거나 OrientDB를 중지하고 하드 드라이브에 공간을 확보 한 다음 데이터베이스를 다시여십시오. 필요한 최소 공간은 4096MB입니다. 필요한 공간이 이제 4096MB로 설정되었습니다 (storage.diskCache.diskFreeSpaceLimit 매개 변수를 설정하여 변경할 수 있음). ?? DB 이름 = "구성 요소"

시도 :
--stacktrace 옵션으로 실행하여 스택 추적을 가져옵니다. 더 많은 로그 출력을 얻으려면 --info 또는 --debug 옵션으로 실행하십시오. 통찰력을 얻으려면 --scan으로 실행하십시오.

* https://help.gradle.org에서 추가 도움 받기

33 대 건물 건설 실패
11 가지 실행 가능한 작업 : 7 개 실행, 4 개 최신
라는 뜻이네요
도와주세요
@patrick-mc

**Comment by Apple6050** [comment]
@noonmaru 도와주세요

**Comment by Apple6050** [comment]
dmulloy2님 서버 문제였네요 고쳤습니다
감사합니다
