### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by ghost** [noonmaru/tap#12]
어제 변경된 소스코드 변화에 따라 Gradle Task는 어떤것으로 해야지 빌드가 가능하나요?

**Comment by Apple6050** [comment]
**기존 gradlew clean distJar로 빌드가 가능하나요?**

**Comment by ghost** [comment]
shadowJar로 됩니다만 이게 정확한건지는 모르겠네요

Command Prompt : gradlew clean shadowJar
Powershell : .\gradlew clean shadowJar

Linux Systems : ./gradlew clean shadowJar

**Comment by ghost** [comment]
빌드된 파일은 .\build\libs에 있어요.

**Comment by Apple6050** [comment]
**저도 그정도는 압니다.** @qogusdn1017

**Comment by qogusdn1017** [comment]
.

**Comment by noonmaru** [comment]
3.0.0 버전부터는 딱히 빌드할 이유가 없습니다.
더 이상 플러그인으로 지원하지 않고 필요한 플러그인에서 의존성 추가하시고 shadowJar로 빌드하시면 됩니다.

이전 버전의 컴파일 버전이 필요하시다면 release탭에 가셔서 2.x.x 버전 다운로드하시면됩니다
