### ISSUE TITLE
3.0.0부터는 tap이 필요한 마인크래프트 플러그인은 어떻게 사용해야 하나요?

### ISSUE THREAD

**Issue by minejango2** [noonmaru/tap#13]
3.0.0부터는 tap이 필요한 마인크래프트 플러그인은 어떻게 사용해야 하나요? shadowjar를 어떻게 사용하는지 잘 모르겠습니다...

**Comment by noonmaru** [comment]
예제 두개입니다.

https://github.com/noonmaru/psychics/blob/master/build.gradle.kts
https://github.com/noonmaru/tap-sample-plugin/blob/master/build.gradle.kts

이전에는 Tap을 플러그인으로 연동해서 사용했다면 플러그인마다 자신의 Tap을 가져가는걸로 변경했습니다.

이유는 너무 잦은 버전 변경으로 인해 의존하는 플러그인들이 Tap의 코드 변화를 따라가기 벅차고 독립성을 지원하기 위해 바꾸었습니다.

shadowJar 태스크 안에 tap 경로를 relocate 하고 shadowJar 태스크로 빌드하면 됩니다.

shadowJar는 종속성 코드를 jar안에 포함시킬 수 있는 기능을 가진 gradle 플러그인입니다.
