### ISSUE TITLE
빌드오류

### ISSUE THREAD

**Issue by Trashnokdu** [noonmaru/tap#18]
> Task :v1_13_R2:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':v1_13_R2:compileKotlin'.
> Could not resolve all files for configuration ':v1_13_R2:compileClasspath'.
   > Could not find org.spigotmc:spigot:1.13.2-R0.1-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
       - file:/C:/Users/S/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/S/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/spigot-1.13.2-R0.1-SNAPSHOT.pom
     Required by:
         project :v1_13_R2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
8 actionable tasks: 1 executed, 7 up-to-date
이에러가 뜹니다

**Comment by jini5012** [comment]
https://maven.notfab.net/SpigotMC/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/ 여기에 들어가셔서 spigot-1.13.2-R0.1-SNAPSHOT.pom 이거를 다운로드 하시고 C:/Users/S/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT 이 파일을 컴퓨터에 만드시고 다운로드한거를 C:/Users/S/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT 이 파일에다가 넣으시고 다시한번 해보시면 될겁니다

**Comment by patrick-choe** [comment]
> https://maven.notfab.net/SpigotMC/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT/ 여기에 들어가셔서 spigot-1.13.2-R0.1-SNAPSHOT.pom 이거를 다운로드 하시고 C:/Users/S/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT 이 파일을 컴퓨터에 만드시고 다운로드한거를 C:/Users/S/.m2/repository/org/spigotmc/spigot/1.13.2-R0.1-SNAPSHOT 이 파일에다가 넣으시고 다시한번 해보시면 될겁니다

웹 상의 파일을 받아 직접 넣기 보다는, Spigot BuildTools를 사용하시기를 바랍니다

**Comment by jini5012** [comment]
아 그러면 되겠네요

**Comment by jini5012** [comment]
이슈를 닫아도 되지 않을 까요?
