### ISSUE TITLE
Tap 플러그인 관련 추가적인 질문

### ISSUE THREAD

**Issue by devil0414** [noonmaru/tap#22]
Tap 플러그인으로 코딩할 때 FakeProjectile은 어떻게 사용하는 건가요?
FakeProjectile을 쓰는 방법 좀 알려주세요.

**Comment by noonmaru** [comment]
FakeProjectileManager 객체를 생성하여 틱마다 update를 호출해주세요

이후 FakeProjectile을 상속한 객체를 launch에 넣어주시면됩니다.

**Comment by devil0414** [comment]
감사합니다. 이슈 닫겠습니다.

**Comment by devil0414** [comment]
실례지만 FakeProjectileManager의 초기값을 어떻게 설정해야 하나요?

**Comment by devil0414** [comment]
실례지만 어떻게 Fakeprojectilemanager의 초기값을 설정 해야 하나요?

**Comment by devil0414** [comment]
@noonmaru

**Comment by devil0414** [comment]
tap-1.0을 모드로써 적용시킬 수 있나요?

**Comment by devil0414** [comment]
@noonmaru
