### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by devil0414** [noonmaru/tap#27]
Custom-entity-bukkit모드는 어떻게 적용시키는지 알려주세요. Custom-entity-bukkit모드를 실행하기 위한 환경도 알려주세요. Custom-entity-bukkit에 이슈를 달 수가 없어서 여기에 이슈를 답니다.

**Comment by devil0414** [comment]
@noonmaru

**Comment by devil0414** [comment]
@patrick-mc

**Comment by qogusdn1017** [comment]
직접빌드하시고 사용하시면 됩니다. 빌드방법은 다른 이슈내용들 찾아보시거나 검색하면 나옵니다.

굳이 맨션하면서 까지 잘못된 곳에 이슈를 달 필요성은 없어보입니다.

**여긴 질문게시판이 아닙니다.**

**Comment by devil0414** [comment]
커스텀엔티티가 닫아서 그 쪽에 이슈를 달지 못하기 때문에 여기에 다는 겁니다.

**Comment by devil0414** [comment]
커스텀엔티티를 적용했을 때 커스텀엔티티가 작동하지 않아요

**Comment by devil0414** [comment]
엔티티의 크기하고 색깔이 안 바뀌어져요.

**Comment by devil0414** [comment]
@noonmaru

**Comment by patrick-mc** [comment]
Custom Entity 프로젝트는 (제가 알기로는) forge 이 적용하는 모드가 필요한데, 현재 해당 forge 코드는 공개되어 있지 않은 것으로 알고있습니다. 따라서, custom entity를 현재 사용하는 것은 불가능할겁니다.

GitHub에서 archived 된 프로젝트의 경우 읽기 전용으로 바뀌어 issue와 pr 작성이 불가능한데, 보통은 추가 지원계획이 없는 레포지토리이니 굳이 다른 레포에 직접적인 관련 없는 이슈 작성은 좋지 않습니다.

**Comment by devil0414** [comment]
감사합니다.
